### ISSUE TITLE
Zbiórka objazdowa odpadów niebezpiecznych

### ISSUE THREAD

**Issue by psielach** [wyrzucto/wyrzuc.to#14]

**Comment by KrzysztofMadejski** [comment]
@psielach Tych danych w końcu nie otrzymaliśmy? upewniam się..

**Comment by KrzysztofMadejski** [comment]
Powinny być zaciągane stąd: https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/ZUT-selektywna-niebezpieczne.xlsx
