### ISSUE TITLE
Stworzyć stage serwer

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#16]
- [x] - Automatyczne testy
- [ ] - Jak testy przechodzą to wdrożenie na serwer stage

**Comment by KrzysztofMadejski** [comment]
Automatyczne testy są już: https://codeship.com/projects/57950/builds/3674420

Ale wywala się deploy na heroku przez sqlite3 (heroku nie obsługuje go). Teoretycznie sqlite3 nie powinien być wykorzystywany, bo jest w grupie dev tylko, ale z jakiegoś powodu assets:precompile się do niego odwołuje:
```
Running: rake assets:precompile DEPRECATION WARNING: Paths in SQLite3 database URLs of the form `sqlite3:///path` will be treated as absolute in Rails 4.2. Please switch to `sqlite3:dbname`. (called from <top (required)> at /tmp/build_39bc4e36e08b51cdfbf29a9be95ed2d9/config/application.rb:7) rake aborted! Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
```

**Comment by sliwecki** [comment]
@KrzysztofMadejski w database.yml w sekcji production zmieniłem na postgresa. Teraz jest ok. Jeśli deploye z codeshipa maja tez byc robione przez capistrano to należny dodać tego gema do aplikacji.

**Comment by KrzysztofMadejski** [comment]
http://wyrzucto.herokuapp.com/
Działa zajebiście! Dzięki wielkie! :)

Myślałem o postawieniu Continous Integration na serwerze kodujdlapolski.pl i hostowanie tam projektów, ale nie znam się na tym niestety.

@psielach zajrzysz? Co jest z mapką?
