### ISSUE TITLE
Moduł: Geokodowanie adresów

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#22]
Pogadać z Biurem Informatyki, czy nie mogą udostępnić aktualnej mapy po WFS, bo tu wyszukiwanie adresów działa: http://mapa.gdansk.gda.pl/Plan/Mapa.aspx

To są najbardziej aktualne dane.

Póki tego nie mamy, musi wystarczyć geolokalizacja z użyciem OSM, np. http://nominatim.openstreetmap.org/search?format=json&country=pl&street=cytrowa%2010

Niech interfejs będzie stały do tego modułu, będzie w przyszłości można wybierać silnik.

BTW: Mapzen zrobił fajny silnik do podpowiadania adresów na bazie ElasticSearch https://mapzen.com/pelias

**Comment by KrzysztofMadejski** [comment]
Gdy jest rzucany wyjątek `Google Geocoding API error: over query limit.` to przetwarzanie adresów powinno się na daną chwilę zakończyć. Obecnie po takim wyjątku i tak dla każdej pozycji podejmowana jest próba geokodowania.

**Comment by KrzysztofMadejski** [comment]
Dostaliśmy mapę adresów z biura informatyki: https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/gdansk_adresy.geojson

Z plików dbf/shp/shx (w zip) po konwersji do geojson (ogr2ogr) trzeba jeszcze:
- przekonwertować układ współrzędnych z EPSG:2177 (do standardowego WGS84, czyli EPSG:4326)
- przekonwertować kodowanie znaków z dbf-owego IBM850 (chyba, bo LibreOffice to pociągnął, iconv nie) do UTF-8.

**Comment by KrzysztofMadejski** [comment]
Pozostaje wykorzystanie bazy miejskiej w celu zwiększenia dokładności. Google Geocoding może być wykorzystany jako backup gdy adresu nie ma.

Baza mapująca adres -> lokalizację powinna być osobną tabelą w bazie. (bo adresy powtarzają się w wielu źródłach danych)

**Comment by ekubal** [comment]
Dane zostały zaimportowane. Mam wątpliwości co do poprawnego działania na Heroku. Import korzysta z klasy Tempfile, która wg dokumentacji zachowuje się tak:

*When a Tempfile object is garbage collected, or when the Ruby interpreter exits, its associated temporary file is automatically deleted.*

Poza tym, Heroku nie wspiera zapisu plików na dysk. @sliwecki  czy Sidekiq gdzieś jest uruchomiony i wykonuje zadania, które wysyłają się do kolejki?

**Comment by KrzysztofMadejski** [comment]
Finalnie to nie będzie chodziło na heroku, tylko na naszym serwerze.

**Comment by sliwecki** [comment]
@ekubal na heroku import nie powinien dzialac do tam nie ma nawet sidekiqa,
mamy serwer dla tej aplikacji i wszystko tam jest poinstalowane. Wiec jesli
robisz zmiany to zaciagaj je na tym serwerze i tam testuj (jak nie masz
danych to podbij do mnie priv). Heroku w sumie mozna usunac. *Tempfile
mozesz zmienic na File lub cos innego, aby nie rodzilo problemow w
przyszlości. Fajnie tez by bylo gdybys takie dlugie metody
(https://github.com/wyrzucto/wyrzuc.to/blob/master/app/models/location.rb#L12
<https://github.com/wyrzucto/wyrzuc.to/blob/master/app/models/location.rb#L12>)
implementował w  servisach, wtedy bedzie czyściej.*

2015-07-09 13:29 GMT+02:00 Krzysiek Madejski <notifications@github.com>:

> Finalnie to nie będzie chodziło na heroku, tylko na naszym serwerze.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/22#issuecomment-119920550>.
>



-- 
...::: damianO     sD   :::...

**Comment by ekubal** [comment]
Zaktualizowałem import zbiórek odpadów niebezpiecznych, dzisiaj bym jeszcze chciał sprawdzić/zmienić import punktów odbioru leków.

**Comment by KrzysztofMadejski** [comment]
Zauważyłem, że terminy odbioru leków pojawiają się w wyszukiwarce z prawej strony. Nie powinny, gdyż to jak z odpadami selektywnymi: pojemniki są okresowo opróżniane (mamy te informacje), ale użytkowników końcowych te terminy nie interesują. Podobnie dymki leków nie powinny zawierać terminów. Import może je olewać (jeżeli jeszcze tego nie importuje).

**Comment by ekubal** [comment]
Czyli z prawej strony aptek w ogóle nie będzie i będą się tylko punkty na mapie pokazywać?

**Comment by KrzysztofMadejski** [comment]
Zgadza się.

2015-07-13 19:05 GMT+02:00 ekubal <notifications@github.com>:

> Czyli z prawej strony aptek w ogóle nie będzie i będą się tylko punkty na
> mapie pokazywać?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/22#issuecomment-120994608>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ekubal** [comment]
Zmienione, już online.

**Comment by ekubal** [comment]
Przerobione całe wyszukiwanie miejsc w pobliżu aby korzystało z tej bazy geojson. Do sprawdzenia czy nie pojawiły się jakieś głupoty.

**Comment by KrzysztofMadejski** [comment]
Śmiga bardzo ładnie.
