### ISSUE TITLE
Parser z XLSX niepoprawnie rozpoznaje kolumny w pliku

### ISSUE THREAD

**Issue by psielach** [wyrzucto/wyrzuc.to#25]
Parser tworzy kolumny ulica, dzielnica ale zamiast dni tygodnia pojawia się jakis dziwny float - wartości np. 5.0, 3.0

**Comment by psielach** [comment]
parser CSV dzialał bez problemu, xlsx też gdy nie ma nagłówków, chodzi jednak o to żeby wgrywac pliki tak jak dostajemy je od miasta

**Comment by KrzysztofMadejski** [comment]
@sliwecki spojrzysz na to? 
To chyba siedzi tu: https://github.com/wyrzucto/wyrzuc.to/blob/master/app/services/import_data.rb

@psielach musiał kasować nagłówki z plików xlsx, bo inaczej nie udawało się ich importować.

W ogóle warto byłoby się zdzwonić i przegadać panel admina. Zastanawiamy się w jakiej formule powinniśmy otrzymywać dane od miasta. Ja głosowałem za tym, żeby to były xlsx, na których urzędnicy na co dzień pracują, tak żeby nie musieli zmieniać narzędzi. Jakby musieli przeklikiwac dane do naszego systemu to w praktyce byśmy dostawali update'y raz na rok. :)

**Comment by sliwecki** [comment]
@KrzysztofMadejski mozesz wysłać mi plik ktory sie zle zaczytuje ? Zrobilem pare zmian pare dni temu w parserze i wydaje mi sie ze juz zaczytuje dane prawidłowo do bazy. Ewentualnie sprawdz czy obecnie dalej zle zaczytuje -> rake import_data

**Comment by KrzysztofMadejski** [comment]
@psielach przetestuj to proszę na plikach z nagłówkiem i powiedz, który konkretnie nie wchodzi i z jakim błędem
