### ISSUE TITLE
Doprowadzić do builda na heroku

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#26]
Czemu rake assets:precompile chce korzystać z sqlite3, kiedy ten gem powinien być wykorzystywany tylko w środowisku development.

https://codeship.com/projects/57950/builds/3674420

**Comment by KrzysztofMadejski** [comment]
Zobaczyłem teraz, że na heroku nie ładują się skompilowane assety:
```
GET 404 http://wyrzucto.herokuapp.com/assets/application-3942007d31710307dd44000cb1f768c9.css 
wyrzucto.herokuapp.com/:6 
GET 404 http://wyrzucto.herokuapp.com/assets/application-fad8ba703669718c2cfd775c724ac017.js 
```

Przez co nie ładuje się mapa, ani style. Jak patrzę w logi heroku to najpierw prekompiluje assety, a później usuwa. Bez sensu!
https://dashboard.heroku.com/apps/wyrzucto/activity/builds/7306900a-3fd5-4643-a569-c6392cb8688a
```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Asset precompilation completed (2.64s)
       Cleaning assets
       Running: rake assets:clean
```

**Comment by sliwecki** [comment]
@KrzysztofMadejski  rake assets:clean czysci stare assety. Kazdy ma unikatowy fingerprint.Problem tu jest z  serwerem heroku i rails 4. Dodalem gema od heroku ktory zalatwia sprawe, teraz powinno zaciagac assety.

**Comment by KrzysztofMadejski** [comment]
Działa, jesteś wielki! :)

**Comment by KrzysztofMadejski** [comment]
@psielach spojrzyj na http://wyrzucto.herokuapp.com/ czy u Ciebie to wygląda podobnie. Nie działa mi wyszukiwanie górne i boczne (mapka jest na środku oceanu).

@sliwecki: masz do polecenia jakiś fajny soft CI, który można by postawić na naszym serwerze, żeby to wdrażał na bieżąco? Jenkins, Hudson?

Może jak będzie to tego łatwy dostęp przez ssh to łatwiej będzie debuggować produkcję.

**Comment by sliwecki** [comment]
moge polecic Jenkinsa bo z nim pracowalem w duzej firmie i sie spisywal

**Comment by psielach** [comment]
u mnie aplikacja wygląda inaczej, brakuje tutaj pól, może jak zmienie wygląd to zacznie dobrze wyświetlać.
