### ISSUE TITLE
Gabaryty

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#29]
Wciąganie do bazy z pliku

Po podaniu adresu na liście wyników z terminami zawsze pojawia się zbiórka wielkogabarytowa (pewnie jako ostatnia pozycja). Powinna być tam wyświetlana zbiórka w miejscu najbliższym podanego.

Zobacz: https://devcenter.heroku.com/articles/postgis

**Comment by sliwecki** [comment]
Duplikat. issue jest w https://github.com/wyrzucto/wyrzuc.to/issues/31 na ostatniej pozycji
