### ISSUE TITLE
prototyp wyglądu wersji mobilnej

### ISSUE THREAD

**Issue by psielach** [wyrzucto/wyrzuc.to#35]
Paweł: Zamiast zdjęć na przyciskach widziałbym jakieś grafiki, inną czcionkę, kolorystykę i przede wszystkim zmieniony nagłówek. 

Krzysiek: Poniższy widok to strona główna dla "nie zalogowanych" userów
![glowna](https://cloud.githubusercontent.com/assets/9881061/6432454/d6d98436-c052-11e4-9483-937155a0664b.jpg)

Krzysiek: Główna dla zalogowanych - wyświetlamy harmonogram.
"nowa ulica" -> "zmień ulicę"
"Gdzie wyrzucić:" -> "Gdzie wyrzucić?"
![odbior](https://cloud.githubusercontent.com/assets/9881061/6432455/d8701904-c052-11e4-83b4-96cc52e30299.jpg)

Krzysiek: gdy zalogowany user to tu go przeniesie po wybory leków na głównej
Ikonki można odpuścić na rzecz przycisku wstecz
![f2lek](https://cloud.githubusercontent.com/assets/9881061/6432456/da39eb3e-c052-11e4-9b3a-dd9862f1712f.jpg)

Krzysiek: Poniższy widok na pewno bez ikonek. Mapka na całą stronę i przycisk do powrotu do głównej strony. Adresu też nie będzie.
Do tego widoku można się dostać albo klikając na adres z 3 mockupu, albo klikając na kategorię będąc na głównej.
![mapp](https://cloud.githubusercontent.com/assets/9881061/6432457/dc0a558e-c052-11e4-91dc-7e5d716c78af.jpg)

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon: Content pod mobile responsive

**Comment by ArekSoldon** [comment]
@psielach powiedz mi jakie są obowiazujace kategorie rodzajó∑ śmeici pokazywanych na mapie?

**Comment by psielach** [comment]
- na zielono w jaki najbliższy dzień tygodnia nastąpi odbiór odpadów suchych i mokrych
- gdzie znajdują się najbliższe apteki przyjmujące leki przeterminowane
- gdzie są najbliższe pojemniki selektywnej zbiórki odpadów
- kiedy i gdzie odbywają się najbliższe geograficznie i terminowo zbiórki odpadów niebezpiecznych
- kiedy jest najbliższa wystawka - zbiórka gabarytów
- i jeszcze dojdzie baza punktów przyjmowania baterii
