### ISSUE TITLE
Połączenie front-backend

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#36]
Przegadajmy to w najbliższy czwartek. Chodzi o to jakie informacje powinny być wystawiane na stronie głównej podczas ładowania, jakie wystawiane poprzez api dla ajax. Pełen zakres danych, który pozwoli frontowi dobrze działać.

Moim zdaniem powinny się pojawić:
- centrowanie mapy: na gdańsku lub na adresie, który jest aktualnie wybrany
- typy śmieci, które się pojawią w autouzupełnianiu powyżej wraz z pełnymi opisami. Dużo tego nie będzie, więc może się ładować statycznie.
- ajax endpoint podpowiadający adres na podstawie wpisanego (trzeba wybrać dokładnie prawda?)
- ajax endpoint ładujący dane harmonogramu po wybraniu adresu? -> punkt GPS + harmonogram
- endpointy do ajaxowego ładowania punktów na mapie oraz grupowania markerów

**Comment by ArekSoldon** [comment]
Tu jest wersja desktop: 
http://artevia.home.pl/artevia/2015/wyrzucto/

A tutaj mobile:
http://artevia.home.pl/artevia/2015/wyrzucto-mobile/iframe.html
http://artevia.home.pl/artevia/2015/wyrzucto-mobile/

paczki:
https://dl.dropboxusercontent.com/u/19244622/wyrzucto.zip
https://dl.dropboxusercontent.com/u/19244622/wyrzucto-mobile.zip
