### ISSUE TITLE
Na mapie +/-

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#41]
Tak, żeby klikając można było oddalać, nie tylko z kółkiem myszki.

**Comment by staskie** [comment]
Hej,

Czy chodzi o cos takiego?

![41-1](https://cloud.githubusercontent.com/assets/493547/8551200/726d01c0-24d5-11e5-99c2-7f2dd181b9e7.jpg)

**Comment by KrzysztofMadejski** [comment]
Coś takiego właśnie!

On Tue, Jul 7, 2015 at 6:25 PM, Dominik Staskiewicz <
notifications@github.com> wrote:

> Hej,
>
> Czy chodzi o cos takiego?
>
> [image: 41-1]
> <https://cloud.githubusercontent.com/assets/493547/8551200/726d01c0-24d5-11e5-99c2-7f2dd181b9e7.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/41#issuecomment-119260113>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by sliwecki** [comment]
Zamkłem brancha bo mielm to juz w poprawkach ktore robilem ostatnio do
aplikacji i dzis wrzucilem.

W dniu 7 lipca 2015 18:57 użytkownik Krzysiek Madejski <
notifications@github.com> napisał:

> Coś takiego właśnie!
>
> On Tue, Jul 7, 2015 at 6:25 PM, Dominik Staskiewicz <
> notifications@github.com> wrote:
>
> > Hej,
> >
> > Czy chodzi o cos takiego?
> >
> > [image: 41-1]
> > <
> https://cloud.githubusercontent.com/assets/493547/8551200/726d01c0-24d5-11e5-99c2-7f2dd181b9e7.jpg
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wyrzucto/wyrzuc.to/issues/41#issuecomment-119260113
> >.
> >
>
>
>
> --
> Krzysztof Madejski
> Koordynator Koduj Dla Polski, Fundacja ePaństwo
> Code for Poland program manager, ePF Foundation
> http://epf.org.pl
> http://kodujdlapolski.pl
> krzysztof.madejski@epf.org.pl
> +48 664 082 823
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/41#issuecomment-119267406>.
>



-- 
...::: damianO     sD   :::...

**Comment by KrzysztofMadejski** [comment]
Dzięki @staskie za pomoc :-)
Na tym etapie sobie poradzimy ze wszystkim, ale jakbyś chciał pomóc w rozwijaniu projektu w przyszłości to obserwuj repo. :)

**Comment by staskie** [comment]
Ciekawy projet, tak wiec trzymam kciuki i bede tu czasami zagladal :+1:

**Comment by ekubal** [comment]
widzę, że 3 osoby to równolegle zrobiły.

Jest już w origin/master i online: http://wyrzuc.to/
