### ISSUE TITLE
 Import fraz: istniejące powinien zostawiać, brakujące dodawać

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#42]
Proces importu:

Dla każdej frakcji:
Dla każdej frazy:
- jeżeli fraza istnieje, zaktualizuj jej frakcję (jeżeli to potrzebne)
- jeżeli fraza nie istnieje, dodaj ją przypisując frakcję

Wszystkie nowe frakcje powinny być automatycznie dodane przez improt

**Comment by KrzysztofMadejski** [comment]
FRAKCJE są drukowanymi
frazy poniżej

[0630 slownik-odpady-excel.xlsx | uploaded via ZenHub](https://files.zenhub.io/55963e1d38c044d41e442d76)

Ten plik się jeszcze zmieni (frakcja "mokre,suche,zmieszane" zostanie rozbita na "mokre" i "suche").

Stąd punkt 1, dla przykładu: 
Jeżeli areozol byl przypisany do "mokre, suche, zmiesznae", a teraz jest w "suche" to to jego FRAKCJA powinna zostać zaktualizowana.

**Comment by KrzysztofMadejski** [comment]
W podpowiedziach powtarzają się duplikaty, np. "tworzywa sztuczne". Czy nowy ponowne importy nie duplikują?

**Comment by KrzysztofMadejski** [comment]
Dane siedzą w tym pliku: https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/slownik-odpady-frakcje.xlsx

**Comment by ekubal** [comment]
To były jakieś dane z 3 czerwca, import wygląda ok, więc bym założył, że po drodze zostało to rozwiązane i monitorował.

**Comment by KrzysztofMadejski** [comment]
istniejących nie aktualizuje, nie dodaje też nowych fraz. Wydaje mi się, że powinno wyglądać to nastepujaco:

```ruby
module ImportData
  class Phrases < Base

    def import
      excel.sheet('Arkusz1')
      (1..5).each do |col|
        (2..excel.last_row).each do |row|
          next if excel.cell(row, col).nil?

          phrase = Phrase.find_by_name(excel.cell(row, col))

          if phrase.nil?
            Phrase.create(data(row, col))
          else
            phrase.update_attributes(data(row, col))
          end
        end
      end
    end

    private

    def data(row, col)
      {
        name: excel.cell(row, col),
        fraction_id: fraction(col).id,
      }
    end

    def fraction(col)
      fraction_name = excel.cell(1,col)

      Fraction.find_or_create_by(name: fraction_name)
    end
  end
end
```

**Comment by sliwecki** [comment]
z tego co widze to sie plik zmienil, a gdzie to importujesz na heroku ? jak tak to tam nie zaimportujesz bo nie ma sidekiq.

**Comment by KrzysztofMadejski** [comment]
Juz chodzi.
