### ISSUE TITLE
Odpady mokre/suche/zmieszane nie powinny wyświetlać się na mapie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#47]
Bo to są prywatne punkty. Powinny pojawiać się za to terminy w wynikach wyszukiwania dla danego adresu.

**Comment by ekubal** [comment]
@KrzysztofMadejski - chodzi o stronę główną oraz podstronę po wpisaniu adresu w prawym panelu?

**Comment by KrzysztofMadejski** [comment]
Znika kategoria oraz punkty z mapy:
![wyrzucto](https://cloud.githubusercontent.com/assets/849975/8567219/dfc8d8a0-2563-11e5-9847-1556d3a47d00.PNG)

Informacja o terminach odpadów wyświetla się po wpisaniu adresu w prawym panelu.

**Comment by ekubal** [comment]
Chyba już http://wyrzuc.to/
