### ISSUE TITLE
Odpady niebezpieczne

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#48]
Odpady niebezpieczne to czasowe zbiórki (np. "14 listopada w godz. 13:20 -13:40 odbieramy niebezpieczne odpady przy Grunwaldzkiej 10").

- [ ] Na glównej mapie powinny wyświetlać się punkty z najbliższych 14 dni (ilość dni konfigurowalna)
- [ ] Po najechaniu punktu powinny się wyświetlać:
  - adres 
  - dodatkowy opis miejsca odbioru
  - data ("wtorek, 12 sierpnia 2015, w godzinach 12:15 - 12:30)

Kiedyś do potencjalnego wdrożenia:
- [ ] Po wybraniu adresu najbliższy punkt odległościowo (w jakiejś rozsądnym okresie czaowym - 2 mies?) wraz z datą powinien być wyświetlany na liście (po kliknięciu mapa centrowana na nim i popup otwierany)

**Comment by ekubal** [comment]
@KrzysztofMadejski czyli tutaj na głównej tego nie powinno być? Tylko po wpisaniu adresu w prawym panelu?

**Comment by KrzysztofMadejski** [comment]
Do przegadania na tel

**Comment by KrzysztofMadejski** [comment]
Zaktualizowałem opis

**Comment by ekubal** [comment]
@KrzysztofMadejski czy tutaj importowany powinien być ten plik: https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/ZUT-selektywna-niebezpieczne-2015-10.xlsx ?

Jak patrzę na skrypt importujący to chyba dopuszczalne jest, aby w polu Data znajdowało się kilka dat rozdzielonych spacjami. Moim zdaniem to trochę bez sensu, bo trzeba zakładać, że godziny są takie same. Również wyszukiwanie efektywniej zrobić gdy poszczególne zbiórki pod jednym adresem to osobne rekordy

**Comment by KrzysztofMadejski** [comment]
Kilka dat w jednym rekordzie jest sensowne w pliku jest sensowne, ponieważ godziny wynikają z rozkładu jazdy samochodu zbierającego. Aby nie kombinować rozkład jest zawsze ten sam tylko dni się zmieniają (powtórzony przejazd np. po miesiącu).

Jak to zrealizować wewnętrznie, żeby się sensownie wyszukiwało pozostawiam Tobie. Ale też bym to rozbił na osobne wpisy w bazie.

**Comment by ekubal** [comment]
Tak, zdecydowanie sensowniej będzie jak jeden rekord to będzie jedna zbiórka w określonym miejscu. Jest jeszcze kwestia adresów - przykładowo w arkuszu jest: 
ul. Hermesa 14-56

Myślę, że rozbijać tego na zbiórki w każdym budynku z zakresu 14 do 56 nie ma sensu i zostawić to trzeba w takiej postaci. W związku z tym pytanie, czy korzystać tam z bazy geojson z adresami, a jeśli tak to jakiego adresu użyć przy **ul. Hermesa 14-56**?

**Comment by KrzysztofMadejski** [comment]
W takich przypadkach importer powinien zwracać błąd. Trzeba takie przypadki
poprawiać ręcznie, tak jak mówiłem powinien być jeden adres per rekord (bo
odpowiada to pojedynczemu miejscu zbiórki).

W tym przypadku w opisie jest parking, patrząc w google
https://www.google.pl/maps/place/Hermesa,+Gda%C5%84sk/@54.4227383,18.4812966,345m/data=!3m1!1e3!4m2!3m1!1s0x46fd9f89ed1f4ec9:0xbe55dc7cea3b4811
albo chodzi o Hermesa 4, albo ten na poboczu przy Hermesa 14. Z listą
błędów trzeba się będzie udać do odpowiedzialnej komórki i dopytywać.




2015-07-10 19:48 GMT+02:00 ekubal <notifications@github.com>:

> Tak, zdecydowanie sensowniej będzie jak jeden rekord to będzie jedna
> zbiórka w określonym miejscu. Jest jeszcze kwestia adresów - przykładowo w
> arkuszu jest:
> ul. Hermesa 14-56
>
> Myślę, że rozbijać tego na zbiórki w każdym budynku z zakresu 14 do 56 nie
> ma sensu i zostawić to trzeba w takiej postaci. W związku z tym pytanie,
> czy korzystać tam z bazy geojson z adresami, a jeśli tak to jakiego adresu
> użyć przy *ul. Hermesa 14-56*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/48#issuecomment-120476850>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ekubal** [comment]
Zaimportowałem bazę, przeszło 138 rekordów. Ustawiłem od razu poprawne etykiety (adres, opis, data, godziny).

Konfiguracja ilości dni możliwa z panelu administracyjnego: http://wyrzuc.to/service/settings

**Comment by ekubal** [comment]
Pozmieniałem apteki/niebezpieczne aby wiele zbiórek było w jednym rekordzie, ale stworzyłem odpowiedni skrypt, który powinien aktualizować daty następnej zbiórki.

**Comment by ekubal** [comment]
Moje pytanie, czy coś tutaj jeszcze jest do zrobienia?

**Comment by KrzysztofMadejski** [comment]
Nie.

On Mon, Jul 13, 2015 at 7:03 PM, ekubal <notifications@github.com> wrote:

> Moje pytanie, czy coś tutaj jeszcze jest do zrobienia?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/48#issuecomment-120994229>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by KrzysztofMadejski** [comment]
Na Heroku mam 500tke jak wybieram z listy"Hermesa 16":http://wyrzuc.to/home/search_places

**Comment by ekubal** [comment]
Jakiś błąd leciał przez brak tygodnia przy jednym śmieciu. Dodałem filtrowanie.

**Comment by ekubal** [comment]
Do sprawdzenia.
