### ISSUE TITLE
Import - przetwarzanie złożonych numerów budynków

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#49]
Import powinien obsługiwać następujące formaty numerów budynków:

**1 Zakres:**
- x-y, np. 27-34
- x do końca, np. 56 do końca

**2 Parzystość:**
<zakres> (parz.|nieparz.|parzyste|nieparzyste)
np. "4 do końca parz." 

**3 Połączenie powyższych przez przecinek i średnik:**
np. "4 do końca parz.; 21-51 nieparzyste"

Import wymaga wgrania wcześniej bazy adresowej (#22)

**Comment by ekubal** [comment]
@KrzysztofMadejski czy możemy założyć, że numery są wyłącznie liczbami (czy może być np. 12A)?

Myślę, że te opisy "do końca", "parzyste", "nieparzyste" mogłyby korzystać z dostarczonej bazy adresów, na początek z obsługą:
* 12
* 12,16,18
* 12-24
* 12-80 parzyste;17,19
* 12-30 parzyste;15-23 nieparzyste
* 12 do końca
* do 12

**Comment by KrzysztofMadejski** [comment]
Pojawia się trochę tych z literkami przyklejonymi, więc też powinien je obsługiwać.

Lista pod testy wygląda dobrze. :)

**Comment by KrzysztofMadejski** [comment]
Obsługa złożonych numerów budynków dotyczy importu:
- [ ] [śmieci komunalnych](https://github.com/wyrzucto/wyrzuc.to/tree/master/public/dane_miejskie/zdiz_komunalka)
- [ ] [gabaryty/wystawki](https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/zdiz_gabaryty) (numery budynków w nawiasach kwadratowych, nie w osobnej kolumnie)

Pojedyncze adresy budynków powinny znajdować się w danych:
- [ ] [odpadów niebezpiecznych i zbiórki selektywnej](https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/ZUT-selektywna-niebezpieczne-2015-10.xlsx)
- [ ] [odbioru leków](https://github.com/wyrzucto/wyrzuc.to/blob/master/public/dane_miejskie/Harmonogram-apteki-2015.xlsx)

**Comment by ekubal** [comment]
Leki zaktualizowałem, podobnie odpady niebezpieczne.

Jutro bym chciał śmieci komunalne przerobić. @KrzysztofMadejski rozumiem, że tam adres w stylu "Wąska 1-19" zmieniamy na 19 różnych punktów? Wtedy na mapie w wynikach dla "Wąska" nie pojawia się nic, natomiast dla "Wąska 15" już się pokazuje odpowiedni wpis z prawej strony?

**Comment by KrzysztofMadejski** [comment]
Wąska 1-19 zmieniamy na 19 punktów powiązanych z adresami. Działanie
dokładnie opisałeś. :)

2015-07-13 20:07 GMT+02:00 ekubal <notifications@github.com>:

> Leki zaktualizowałem, podobnie odpady niebezpieczne.
>
> Jutro bym chciał śmieci komunalne przerobić. @KrzysztofMadejski
> <https://github.com/KrzysztofMadejski> rozumiem, że tam adres w stylu
> "Wąska 1-19" zmieniamy na 19 różnych punktów? Wtedy na mapie w wynikach dla
> "Wąska" nie pojawia się nic, natomiast dla "Wąska 15" już się pokazuje
> odpowiedni wpis z prawej strony?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/49#issuecomment-121009030>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ekubal** [comment]
@KrzysztofMadejski plik 5 sektora zdiz_gabaryty ma niestandardowy format, pozostałe zaktualizowałem i właśnie próbuje zaimportować z uwzględnieniem rozbicia na konkretne numery budynków.

**Comment by KrzysztofMadejski** [comment]
Tak, 5 sektor miasto ma dopasować formatowaniem do reszty.
