### ISSUE TITLE
Wyświetlanie dni odbioru odpadów komunalnych

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#55]
Poprawki przy wyświetlaniu harmonogramów odbioru śmieci komunalnych po podaniu konkretnego adresu:

1) Warto połączyć powtarzające się dni i wylistować pod nimi jakie odbiory są prowadzone.

![wyrzucto-harmonogram](https://cloud.githubusercontent.com/assets/849975/8644973/a20bf6e4-2943-11e5-8884-78476d6d2919.PNG)

2) Istnieją ulice, na których znajduje się zabudowa zarówno wielolokalowa, jak i jednorodzinna. Nie posiadamy danych jaką zabudową jest konkretny adres, a terminy odbioru przeważnie są różne. Dlatego przy opisie powinno pojawić się oznaczenie z jakich lokali dotyczy dana zbiórka.

Dla przykładu: W pierwszym sektorze zbiórki odpadów komunalnych występuje ulica Biegańskiego, na której są oba typy zabudowy. W przypadku gdy jest tylko jeden typ zabudowy takie wyszczególnienie nie musi być wyświetlane.

Kombinując 1 i 2 myślałem o czymś takim (@ArekSoldon popraw jeżeli uważasz, że to inaczej mogłoby być ułożone)
![wyrzucto-harmonogram-propozycja](https://cloud.githubusercontent.com/assets/849975/8645269/2516bec8-2946-11e5-9d7b-7060151a473d.PNG)

**Comment by KrzysztofMadejski** [comment]
Inną opcją jest rozbicie na jednorodzinna/wielolokalowa wzg. dni (wtedy mogłyby się pojawić dwie środy).

**Comment by ArekSoldon** [comment]
Podpisu pod spoko, tylko je wyśrodkujmy jak resztę.

**Comment by ekubal** [comment]
Udało mi się chyba pogrupować te dane wg dni. Z tymi wielokanałowymi temat jest do przegadania, to ma dotyczyć zbiórek z plików z katalogu: public/dane_miejskie/zdiz_komunalka ?

**Comment by KrzysztofMadejski** [comment]
Z tego katalogu.

2015-07-13 19:02 GMT+02:00 ekubal <notifications@github.com>:

> Udało mi się chyba pogrupować te dane wg dni. Z tymi wielokanałowymi temat
> jest do przegadania, to ma dotyczyć zbiórek z plików z katalogu:
> public/dane_miejskie/zdiz_komunalka ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/55#issuecomment-120993897>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ekubal** [comment]
Teraz te etykiety powinny się pojawiać już, po rozwiązaniu pozostałych problemów z typami będzie wszystko ok

**Comment by KrzysztofMadejski** [comment]
Śmiga
