### ISSUE TITLE
Ikony agregujące

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#57]
Niech przedstawiają zagregowane ikony https://github.com/wyrzucto/wyrzuc.to/tree/master/public/markers 

Bez rozróżnienia kolorami, bez rozróżnienia na ilość ikon.

https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js

**Comment by ekubal** [comment]
Ja nie wiem czy się da bez liczby to pokazywać.

**Comment by KrzysztofMadejski** [comment]
Pewnie się da (np. ustawić setCalculator(https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js#L380) ktory zwraca pusty `text`)
![wastes_cluster](https://cloud.githubusercontent.com/assets/849975/8670174/d9b346d8-2a1a-11e5-9608-c8663d817fd4.png)

Ale zróbmy to z białymi liczbami na tle:
![wastes_cluster_blank](https://cloud.githubusercontent.com/assets/849975/8670177/df3c142c-2a1a-11e5-991a-2c84229188a8.png)
nie będzie mylące w przypadkach gdy w takim klustrze nie będzie śmieci opakowaniowych widocznych na froncie tego obrazka.

**Comment by ekubal** [comment]
@KrzysztofMadejski każdy rozdzaj śmiecia inna ikona? Są gdzieś przygotowane bez tych ikon?

**Comment by KrzysztofMadejski** [comment]
Nie rozumiem pytania. Teraz każdy rodzaj śmieci ma inną ikonę już. Tutaj chodzi o to, żeby zastąpić ikony klastrów (żółte,niebieskie,czerwone, patrz poniżej)

![agg](https://cloud.githubusercontent.com/assets/849975/8731191/fd0acb2e-2bf5-11e5-9a3a-7a66d7229046.PNG)

na taką ikonę: https://cloud.githubusercontent.com/assets/849975/8670177/df3c142c-2a1a-11e5-991a-2c84229188a8.png

**Comment by ekubal** [comment]
Czyli każdy klaster dowolnego typu odpadów będzie miał taką ikonę?

**Comment by ekubal** [comment]
Wstawione.

**Comment by KrzysztofMadejski** [comment]
Tak! :)
