### ISSUE TITLE
Podpowiedzi u góry

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#59]
Powinny się wyświetlać tylko te, które mają przypisane frakcje. W innym wypadku pojawi się tam sporo niemoderowanych rzeczy.

**Comment by ekubal** [comment]
Czy tam nie są podpowiadane wyłącznie frazy importowane z arkusza?

**Comment by KrzysztofMadejski** [comment]
Wpisz coś czego nie ma w podpowiedziach i daj enter. Doda się do bazy (to
pożądane działania) i od razu będzie podpowiadane (to niepożądane
działanie).

Krzysiek

On Mon, Jul 13, 2015 at 8:41 PM, ekubal <notifications@github.com> wrote:

> Czy tam nie są podpowiadane wyłącznie frazy importowane z arkusza?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/59#issuecomment-121018658>.
>



-- 
Krzysztof Madejski
Koordynator Koduj Dla Polski, Fundacja ePaństwo
Code for Poland program manager, ePF Foundation
http://epf.org.pl
http://kodujdlapolski.pl
krzysztof.madejski@epf.org.pl
+48 664 082 823

**Comment by ekubal** [comment]
Pozmieniałem, dodałem unikalność nazwy (stare mogą się dublować) oraz obowiązkowość pola fraction_id. Powinno być teraz dobrze.

**Comment by KrzysztofMadejski** [comment]
Działa ok!
