### ISSUE TITLE
Problemy ze stylami

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#60]
- [ ] po wybraniu adresu dubluje się strzałka do rozwijania/chowania
- [ ] brak scrollbara gdy jest więcej pozycji  w prawym w menu niż widać

Chrome
![wyrzucto-style](https://cloud.githubusercontent.com/assets/849975/8696014/4dc923d4-2ae9-11e5-930b-d2311bb1c41f.PNG)

**Comment by ekubal** [comment]
Teraz chyba dobrze. Dziwne, że się to popsuło.

**Comment by KrzysztofMadejski** [comment]
Działa, dzięki!
