### ISSUE TITLE
Usunięcie możliwości zakładania kont

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#61]
http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up

Czy poniższe wystarczy?
```ruby
devise_for :users, path_names: {
  sign_up: ''
}
```

**Comment by sliwecki** [comment]
usun :registerable w
https://github.com/wyrzucto/wyrzuc.to/blob/master/app/models/admin.rb#L4

2015-07-15 13:39 GMT+02:00 Krzysiek Madejski <notifications@github.com>:

>
> http://stackoverflow.com/questions/6734323/how-do-i-remove-the-devise-route-to-sign-up
>
> Czy poniższe wystarczy?
>
> devise_for :users, path_names: {
>   sign_up: ''
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/61>.
>



-- 
...::: damianO     sD   :::...

**Comment by KrzysztofMadejski** [comment]
Sorki @sliwecki że to w twoim imieniu. Zrevokuj ten klucz jeżeli Ci to przeszkadza :-)

**Comment by sliwecki** [comment]
@KrzysztofMadejski spoko, luz :p
