### ISSUE TITLE
Zbiórka komunalna - źle matchowane nazwy

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#66]
Na przykładzie Antoniego Antczaka i Władysława Biegańskiego (pewnie wszytkie w ktorych dłuższe nazwy różnią się od krótszych) - dane nie  wczytują się.

W GeoJson są obie formy, więc pewnie złe kolumny są porównywane (długa z xlsx i krótka z geojson). Opierajmy się na krótkiej zawsze.

**Comment by ekubal** [comment]
Czyli brać nazwę z pola "PELNA" ?

**Comment by KrzysztofMadejski** [comment]
Potrzebne było:
- matchowanie po "nazwa skrócona"
- usuwanie zbędnych whitespace
