### ISSUE TITLE
Wyświetlanie na mapie punktów odbioru zużytych baterii

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#69]
Dane na http://serwer.gdansk.pl/otwarty-gdansk/wykaz-miejsc-odbioru-zuzytych-baterii-na-terenie-gdanska/

- [x] Tabela w bazie danych
- [x] Widok i kontroller do importu https://github.com/wyrzucto/wyrzuc.to/tree/master/app/controllers/service
- [x] Proces importu danych https://github.com/wyrzucto/wyrzuc.to/tree/master/app/services/import_data
- [x] Ikonka oraz wyświetlanie na mapie

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon przygotujesz nam ikonkę dla baterii?

**Comment by ArekSoldon** [comment]
![bateria](https://cloud.githubusercontent.com/assets/3994690/9589080/3d733980-502c-11e5-93ec-978982a275de.png)

**Comment by ArekSoldon** [comment]
była od początku :) 
https://dl.dropboxusercontent.com/u/19244622/Archive%20copy%202.zip

**Comment by ekubal** [comment]
@KrzysztofMadejski , a baza tych punktów gdzieś jest dostępna?

**Comment by KrzysztofMadejski** [comment]
Ten plik powinien być importowany:
http://serwer.gdansk.pl/otwarty-gdansk/wykaz-miejsc-odbioru-zuzytych-baterii-na-terenie-gdanska/

On 7 October 2015 at 16:48, ekubal <notifications@github.com> wrote:

> @KrzysztofMadejski <https://github.com/KrzysztofMadejski> , a baza tych
> punktów gdzieś jest dostępna?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/69#issuecomment-146217695>.
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by ekubal** [comment]
Powinno być już widoczne na http://wyrzuc.to.futurecode.pl/

**Comment by KrzysztofMadejski** [comment]
Ku pamięci: trzeba będzie zmienić opis jaki się wyświetla po wpisaniu baterii w górnym oknie, bo teraz nawiguje wyłącznie do niebezpiecznych.

**Comment by ekubal** [comment]
Z tego co widzę, to można ustawić z panelu admina. Tam do kategorii odpadów tylko dodam opcję, żeby się też pojawiły punkty odbioru baterii.
