### ISSUE TITLE
Panel dla pracowników ZUT

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#71]
Panel umożliwiający logowanie pracownikom ZUT w celu zarządzania pojemnikami
- [x] kontrola dostępu (Devise
- [x] layout (jak aktualny panel administracyjny)

**Comment by KrzysztofMadejski** [comment]
- [ ] dla administratora systemu możliwość tworzenia nowych i edycji istniejących kont pracowników ZUT (username to email)

**Comment by ekubal** [comment]
Ja bym to widział jako osobny model nie powiązany z administratorami, bo po co mieszać dwa różne typy użytkowników?
Panel wtedy będzie wyglądał bardzo podobnie, ale kod panelu dla ZUT będzie bardziej odizolowany od panelu admina.


Tutaj https://github.com/ekubal/wyrzuc.to/compare/master...ekubal:zut-panel jest już to przygotowane. Dodatkowo zacząłem tam używać formtastic (mocne uproszczenie widoków formularzy w panelach) oraz refaktoryzować model Waste na kilka dziedziczonych typów odpowiedzialnych za poszczególne rodzaje odpadów.

**Comment by ekubal** [comment]
Panel dla pracowników ZUT: http://wyrzuc.to.futurecode.pl/zut/districts
Login testowy: test@wyrzuc.to
Hasło testowe: test@wyrzuc.to
