### ISSUE TITLE
Panel pojemników dla ZUT

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#72]
- [x] Kontroler/widok dla listy pojemników (nazwa, rejon, dzielnica, pojemniki)
- [ ] Kontroler/widok dodania/edycji pojemnika
  * nazwa lokalizacji, opis, współrzędne GPS, zdjęcie, rodzaje pojemników (szkło bezbarwne, szkło kolorowe, tworzywa sztuczne, makulatura), uwagi dla kierowców, dzielnica, rejon, typ pojemnika, widoczność na wyrzuc.to

**Comment by KrzysztofMadejski** [comment]
- Ulica i numer domu osobno. 
- Ulica podpowiadana z istniejącej bazy, tak żeby nie robiły się duplikaty..
- Możliwość wpisania ilości pojemników danego rodzaju w danej lokalizacji
- Współrzędne na mapie poprzez ustawienie szpilki na mapie

**Comment by ekubal** [comment]
Ten panel też jest przygotowany w https://github.com/ekubal/wyrzuc.to/compare/master...ekubal:zut-panel

**Comment by ekubal** [comment]
Co z pojemnikami, które dodawane są z pliku excela? One też powinny się w tym panelu wyświetlać i być dostępne do edycji?

**Comment by KrzysztofMadejski** [comment]
One przede wszystkim powinny się tam pojawić. Pytanie co ma się stać jak się dodało pojemniki manualnie, a później ktoś zaimportuje plik z excela.. Manualnie dodane pozycje zostaną usunięte, jeżeli też nie zostały wprowadzone do Excela?

@ekubal @virtualkris

**Comment by ekubal** [comment]
To jest dobre pytanie, te dodawane z panelu mogą być oznaczane, jednak wtedy możemy mieć problem z duplikatami.

**Comment by virtualkris** [comment]
Niekoniecznie musimy mieć opcję importu danych pojemników z Excela, to może być zrobione raz na początku np. przez Was, a potem niech ZUT tylko pracuje (dodaje, odejmuje) nowe pojemniki w panelu. Ważniejsza jest opcja EKSPORTU tych danych, żeby mogli je sobie przesyłać mailem w xls, drukować itp.

**Comment by ekubal** [comment]
Tutaj nie wiem na ile ta wstępna lista danych była sensowna - czy zdjęcie, opis są w ogóle potrzebne w formularza edycji/dodania kontenera? Również w tym miejscu nie wiem jaka jest różnica pomiędzy rodzajem a typem kontenera.
