### ISSUE TITLE
Panel pracowników ZUT

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#73]
- [x] Tabela w bazie danych
- [x] Kontroler/widok listy pracowników
- [x] Kontroler widok dodania/edycji pracownika (imię, nazwisko, email (login), hasło)

**Comment by KrzysztofMadejski** [comment]
Dostępne dla administratora wyłącznie.

**Comment by ekubal** [comment]
Słabo niestety sobie to wydzieliłem na branche, jest przygotowane w https://github.com/ekubal/wyrzuc.to/compare/master...ekubal:zut-panel

**Comment by ekubal** [comment]
Tutaj panel: http://wyrzuc.to.futurecode.pl/service/employees

Utworzenie pracownika jest wymagane do logowania do panelu ZUT.

**Comment by virtualkris** [comment]
A to działa? Nie mogę się zalogować przez test@wyrzuc.to

**Comment by ekubal** [comment]
Aktualnie są dwa panele:
1. panel administracyjny (ścieżka http://domena/SERVICE/....) zarządzany przez miasto (login/hasło przykładowe: admin@wyrzuc.to/admin@wyrzuc.to)
2. panel ZUT (ścieżka: http://domana/ZUT/...) zarządzany przez pracowników ZUT (login/hasło przykładowe: test@wyrzuc.to/test@wyrzuc.to)
