### ISSUE TITLE
Panel tras dla ZUT

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#74]
- [x] Tabela w bazie danych
- [x] Kontroler/widok listy tras
- [x] Kontroler/widok listy dodania/edycji trasy
- [ ] Kontroler/widok dodania lokalizacji/pojemnika
- [ ] Zmiana kolejności na liście
- [ ] Usuniecie lokalizacji z listy
- [x] Usunięcie trasy

**Comment by KrzysztofMadejski** [comment]
Dodawanie lokalizacji będzie wyłącznie spośród tych, które są już w bazie. 
Trasa powiązana jest z rejonem - punkty można dodawać wyłącznie z tego rejonu.

Pytanie, czy mają się tu znaleźć wszystkie punkty które są w bazie, czy nie? Czy wszystkie, które się publicznie wyświetlają w wyrzuc.to? 

Jeżeli w panelu #72 dodawane są nowe punkty, czy automatycznie pojawiają się na tych listach?

**Comment by virtualkris** [comment]
Mają się tu znaleźć wszystkie punkty, które są w bazie. Jest ich więcej niż te widoczne na wyrzuc.to (np. niedostępne publicznie pojemniki na terenach różnych obiektów zamkniętych).

**Comment by KrzysztofMadejski** [comment]
@ekubal przemyślisz jak rozwiązać to, żeby na wstępie móc uszeregować całą istniejącą listę, a później wszystkie nowo dodane pozycje w tym regionie były wyszczególnione, tak żeby je ręcznie umieścić na odpowiedniej pozycji na liście?

Rozumiem, że punkty usunięte powinny automatycznie znikać.

**Comment by ekubal** [comment]
Punkty byłyby identyfikowane poprzez adres, prawda? Może jakaś lista z https://jqueryui.com/sortable/ oraz opcjami dodania na koniec (a potem przesunięcie w odpowiednie miejsce) oraz usunięcia punktu?

**Comment by ekubal** [comment]
Panel tras jest przygotowany w https://github.com/ekubal/wyrzuc.to/compare/master...ekubal:zut-panel

Trzeba będzie jeszcze dorobić tam panel umożliwiający zarządzanie punktami na trasie.

**Comment by ekubal** [comment]
Panel tras: http://wyrzuc.to.futurecode.pl/zut/routes

**Comment by ekubal** [comment]
Z tego co się zorientowałem - w importowanych plikach nie ma informacji o regionie, przez co ciężko powiązać punkty z regionem trasy.

**Comment by virtualkris** [comment]
prześlijcie pls login do panelu

**Comment by ekubal** [comment]
Login testowy: test@wyrzuc.to
Hasło testowe: test@wyrzuc.to

**Comment by ekubal** [comment]
Tutaj ważne pytanie z mojej strony - czy pojedynczy punkt (odpady opakowaniowe) może znajdować się na kilku trasach czy tylko na jednej?

**Comment by virtualkris** [comment]
@ekubal muszę zapytać, ale na razie jestem przeziębiony i leżę w łózku :-(

**Comment by virtualkris** [comment]
Dany punkt może być tylko na jednej trasie
