### ISSUE TITLE
Import stref, dzielnic

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#75]
Zaimportowanie listy stref i dzielnic

**Comment by KrzysztofMadejski** [comment]
Żeby były do wyboru w formularzach?

**Comment by ekubal** [comment]
Tak, dokładnie

**Comment by ekubal** [comment]
@KrzysztofMadejski, czy listy są gdzieś dostępne.

**Comment by KrzysztofMadejski** [comment]
Administrator wpisze

**Comment by KrzysztofMadejski** [comment]
Choć to i tak będzie upierdliwe, bo idealnie dzielnice powinny razem z numerami budynków być importowane (patrz geojson), ale chyba nie ma szans tego od miasta wyciągnąć.

**Comment by ekubal** [comment]
W sumie to jest raczej stała pula informacji - może po prostu pełne listy byśmy wprowadzili do aplikacji bez panelu, żeby ktoś przypadkiem czegoś nie usunął. W tym geojson tych informacji chyba nie ma.

**Comment by KrzysztofMadejski** [comment]
Zostawmy panel, zastrzeżmy usuwanie tylko dla głównego admina.

2015-10-09 13:06 GMT+02:00 ekubal <notifications@github.com>:

> W sumie to jest raczej stała pula informacji - może po prostu pełne listy
> byśmy wprowadzili do aplikacji bez panelu, żeby ktoś przypadkiem czegoś nie
> usunął. W tym geojson tych informacji chyba nie ma.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyrzucto/wyrzuc.to/issues/75#issuecomment-146835010>.
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by ekubal** [comment]
Ok, to dzielnice wezmę od razu z https://pl.wikipedia.org/wiki/Podzia%C5%82_administracyjny_Gda%C5%84ska

Jak jest z tymi strefami? Ich jest po prostu 6 tak jak w którymś z pozostałych rodzajów odpadów było określone?

**Comment by KrzysztofMadejski** [comment]
W innych issue widzę numer rejonu, więc pewnie o niego Ci chodziło.

Cytując specyfikację: "rejon (w sumie są 22)"

**Comment by ekubal** [comment]
@KrzysztofMadejski jesteśmy w stanie uzyskać informacje jaką to ma formę (nazwy czy po prostu numery 1-22)? Jeśli nazwy to zamiast importu CSV/excela lepsze byłyby może po prostu standardowe panele?

**Comment by ekubal** [comment]
Panel do dzielnic: http://wyrzuc.to.futurecode.pl/zut/districts

Nie wiem jak wygląda kwestia tych rejonów, ale mogę zrobić coś analogicznego.

**Comment by KrzysztofMadejski** [comment]
@virtualkris: Rejony są numerowane od 1 do 22? Nie mają nazw?

**Comment by virtualkris** [comment]
Nie mają nazw, bo nie odpowiadają granicom dzielnic.

**Comment by ekubal** [comment]
Login testowy: test@wyrzuc.to
Hasło testowe: test@wyrzuc.to

Konto pracownika ustawia z panelu administracyjnego.

**Comment by ekubal** [comment]
Ok, czyli przyjmujemy listę: 
1
2
3
...
21
22

**Comment by ekubal** [comment]
Skoro rejony mamy załatwione jako ponumerowaną listę to zostają dzielnice:
http://wyrzuc.to.futurecode.pl/zut/districts

Myślę, że to już jest w porządku.
