### ISSUE TITLE
Eksport danych pojemników

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#76]
Dostępne filtry:
* dzielnica
* sektor
* typ pojemnika
* trasa

Konieczne jest określenie formatu generowanych plików wyjściowych

**Comment by KrzysztofMadejski** [comment]
XLSX (lub CSV) z polami:
- Lp. 
- Lokalizacja (adres i numer)
- Opis uszczegóławiający
- Dzielnica
- Rejon
- Rodzaj pojemnika (ile pojemników SzB./ SzK./ Tw./ Mak. )
- Typ pojemnika 
- Uwagi dla kierowców

Do potwierdzenia z ZUT.

**Comment by virtualkris** [comment]
XLSX z takimi polami będzie OK.

**Comment by ekubal** [comment]
@virtualkris : które z podanych danych obecnie są już przechowywane?
Chyba tylko lokalizacja i rodzaje pojemników. Reszta powinna być dodana w panelu z kontenerami i/lub importowanym pliku?

**Comment by ekubal** [comment]
@virtualkris, @KrzysztofMadejski wyjaśniło się coś w sprawie tych informacji o pojemnikach?

**Comment by virtualkris** [comment]
Nie wiem, czy rozumiem dokładnie? W panelu muszą mieć możliwość dodania wszystkich informacji o których pisał @KrzysztofMadejski

**Comment by ekubal** [comment]
1. "Opis uszczegóławiający" to jest dodatkowe pole do formularza edycji?
2. "Typ pojemnika" a "Rodzaj pojemnika" czym to się różni?

**Comment by ekubal** [comment]
Jeszcze jedno pytanie:
3. w odpadach mokrych/suchych są jakieś rejony 1-6. Czy to się jakoś łączy z tymi rejonami przy kontenerach?

**Comment by virtualkris** [comment]
trzymajmy się tych pól, które są w pliku doc, który dostaliśmy z ZUT
(wysłałem przed chwilą mailem). Wydaje mi się, że tam jest wszystko i dość
dokładnie opisane.
Dla mnie za dużo jest rozbieżności w pytaniach i tym co ZUT rozrysowało

W dniu 30 października 2015 11:32 użytkownik ekubal <
notifications@github.com> napisał:

**Comment by ekubal** [comment]
Ten plik dużo pomoże.

Aktualnie generuję coś takiego:
Numer;Adres;Opis uszczegóławiający;Dzielnica;Rejon;Szkło bezbarwne;Szkło kolorowe;Tworzywa sztuczne;Makulatura;Typ pojemnika;Uwagi dla kierowców
1;Subisława 23;-;-;-;1;1;2;2;-;-
2;Subisława 22;-;-;-;0;1;1;1;-;-
3;Rybacka 7;-;-;-;1;1;1;1;-;-
4;Pelplińska 5;-;-;-;0;0;1;1;-;-
5;Sztormowa 7;-;-;-;1;1;2;2;-;-
6;Sztormowa 1;-;-;-;1;1;1;1;-;-
7;Pomorska 15;-;-;-;0;1;1;1;-;-


Czy format CSV tutaj byłby w porządku czy konieczny jest Excel?

**Comment by virtualkris** [comment]
Csv ok.
