### ISSUE TITLE
Archiwum list

### ISSUE THREAD

**Issue by ekubal** [wyrzucto/wyrzuc.to#77]
Tego nie do końca rozumiem, czy konieczne jest przechowywanie archiwalnych tras dla kierowców?

**Comment by KrzysztofMadejski** [comment]
Czy każda trasa, która jest eksportowana powinna się tu zapisywać? Jaki format zapisu - kopia PDF/XLS, czy taki który pozwoli jednym kliknięciem na odtworzenie tych tras?

**Comment by virtualkris** [comment]
Tak, potrzebujemy archiwum wszystkich tras w formacie XLS i ewentualnie PDF.

**Comment by ekubal** [comment]
W jakim sensie archiwum? Chodzi o listę tras bieżących i usuniętych? Co w przypadku gdy zmieni/usunie/doda się jeden punkt do jakiejś trasy? Wtedy w archiwum ląduje ona dwukrotnie?

**Comment by virtualkris** [comment]
Jeśli ZUT zmieni coś na liście tras - dajmy na to 30 października, to chcą
mieć w archiwum wersję obowiązującą 29 października itd.

W dniu 30 października 2015 13:18 użytkownik ekubal <
notifications@github.com> napisał:

**Comment by virtualkris** [comment]
Te trasy zmieniają się naprawdę rzadko, więc to nie będą nie wiadomo jak długie listy w archiwum.

**Comment by ekubal** [comment]
Potrzebuję jeszcze informacji jaką rolę ma spełniać to archiwum. Chciałbym po prostu zaplanować które informacje archiwizować, a których nie. Jakie operacje można na takiej trasie wykonywać?

Co w przypadku gdy np. w grudniu usunę punkt znajdujący się na trasie z września? Rozumiem, że na bieżącej trasie on zniknie, a co z archiwalnymi?
