### ISSUE TITLE
Mockup strony głównej

### ISSUE THREAD

**Issue by KrzysztofMadejski** [wyrzucto/wyrzuc.to#8]
Strona główna powinna zawierać:
- Mapa (prezentująca cały Gdańsk, rózne markery dla różnych typów śmieci)
- Wyszukiwanie "Gdzie mam wyrzucić [input box z podpowiedziami]
- "Pokaż terminy odbioru śmieci dla posesji [input box]"

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon podeślij proszę projekt w psd i ikonki wszystkie (recycle, strzałka w prawo, kalendarzyk)

**Comment by KrzysztofMadejski** [comment]
@Cain-Ish czy takie markery dymkowe jak są na mapie można zrobić w CSS czystym? Rzucisz hinta jakiegoś?

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/wyrzucto.zip

psd (w grupach stany bocznego paska)
plus ikony w svg
