### ISSUE TITLE
Przykrywające się wzajemnie oznaczenia na mapie przy zbliżeniu

### ISSUE THREAD

**Issue by andrzejkaszkowiak** [wyrzucto/wyrzuc.to#98]
Oznaczenia znajdujące się w jednym miejscu nachodzą na siebie i przykrywają się wzajemnie w przybliżonym widoku. 

Widok z oddalenia:
<img width="287" alt="screen shot 2016-07-19 at 22 50 24" src="https://cloud.githubusercontent.com/assets/235299/16966078/44e79aaa-4e03-11e6-96fa-a54534d69025.png">

Przybliżony widok lokacji:
<img width="399" alt="screen shot 2016-07-19 at 22 50 41" src="https://cloud.githubusercontent.com/assets/235299/16966079/44e810c0-4e03-11e6-91eb-638c9e8f6905.png">

**Comment by KrzysztofMadejski** [comment]
To uwaga do ludzi z ZUT, żeby trochę rozsuwali te punkty, które się pokrywają. Dzięki za zgłoszenie!

## 

A swoją drogą czy nie jest mylące, że typy wizualizowane jako cluster nie pokrywają się z tym co pod spodem? To był na szybko skonfigurowany [MarkerClusterer](https://github.com/googlemaps/js-marker-clusterer). Ikona grupy jest [pojedynczą ikoną](https://github.com/wyrzucto/wyrzuc.to/blob/master/public/markers/cluster.png), nie ma możliwości wgrania kilku.

Opcją jest przerobienie marker-clusterer, tak żeby sam układał kilka ikon jedna na drugiej zgodnie z typami tego co jest pod spodem. Ale nie wiem jak z wydajnością takiego rozwiązania..

**Comment by venedie** [comment]
Może byłoby to rozwiązanie i może właśnie warto pozostawić cluster tylko inaczej go wizualizować w zależności od przybliżenia? Nie wiem na ile to możliwe i czy będzie to na tyle interaktywne.
