### ISSUE TITLE
Projekt umarł?

### ISSUE THREAD

**Issue by ddziaduch** [wyrzucto/wyrzuc.to#99]
Coś wiadomo? Strona http://wyrzuc.to nie działa :<

**Comment by KrzysztofMadejski** [comment]
Domena wygasła. Podpiąłem serwis pod adres http://wyrzucto.kodujdlapolski.pl/

**Comment by ghost** [comment]
Passenger chyba się wywalił  `502 Bad Gateway`
może jakiś monitoring usługi, hm?

**Comment by KrzysztofMadejski** [comment]
@piotr-zuralski chciałbyś się włączyć w utrzymywanie tego serwisu?

**Comment by gakowalski** [comment]
Na czym polega problem z utrzymywaniem tego serwisu? Teraz jest `502 Bad Gateway`, co jest nie tak?

**Comment by KrzysztofMadejski** [comment]
Nie ma product ownera żadnego - kogoś komu by mocno zależało, żeby projekt stał stabilnie (nie mówiąc już o rozwoju).

**Comment by gakowalski** [comment]
Czy mogę poprosić o dostęp do serwera, aby móc zbadać ten `502 Bad Gateway` i przywrócić normalne funkcjonowanie?

**Comment by KrzysztofMadejski** [comment]
Wpadłem na serwer i wychodzi na to, że service unicorn serwujący aplikację nie był skonfigurowany na autostart i nie wstał, po którymś padzie serwera. Skonfigurowałem to i chodzi: http://wyrzucto.kodujdlapolski.pl/

@gakowalski dziękuję bardzo za zaoferowanie pomocy! Może przy następnym padzie Cię wdrożę? Jakbyś chciał się regularnie wdrożyć w projekt to daj znać, mogę dać Ci prawa admina i będziesz czuwał jakby coś się działo. Pozdrawiam!
